all::
#	docker build --platform=linux/arm64/v8 . -t wcc-aarch64:latest || :
#	docker build --platform=linux/arm/v7 . -t wcc-arm:latest || :
#	docker build --platform=linux/mips64 . -t wcc-mips64:latest || :
#	docker build --platform=linux/loong64 . -t wcc-loong64:latest || :
#	docker build --platform=linux/s390x . -t wcc-s390x:latest || :
#	docker build --platform=linux/ppc64 . -t wcc-ppc64:latest || :
#	docker build --platform=linux/riscv64 . -t wcc-riscv64:latest || :
#	docker build --platform=linux/mips64le . -t wcc-mips64le:latest || :
#	docker build --platform=linux/ppc64le . -t wcc-ppc64le:latest || :
#	docker build --platform=linux/386 . -t wcc-386:latest || :

	docker build --platform=linux/sparc64 . -t wcc-sparc64:latest || :
	
run::
#	docker run --platform=linux/arm64/v8 -it wcc-aarch64:latest /bin/bash
